name: webview_location
description: A Simple flutter package designed to display Google Maps locations by place name in a WebView for both Android and iOS platforms.
version: 0.0.3
homepage: https://github.com/i-aiymen/webview_location
repository: https://github.com/i-aiymen/webview_location

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
